"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Workflow, Plus, Mail, Clock, ChevronRight, Zap, Users, Eye } from "lucide-react";

const BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

const CHANNEL_ICON: Record<string, string> = {
  email: "✉️",
  linkedin: "💼",
  phone: "📞",
};

const CHANNEL_COLOR: Record<string, string> = {
  email: "text-blue-300 bg-blue-500/10 border-blue-500/30",
  linkedin: "text-cyan-300 bg-cyan-500/10 border-cyan-500/30",
  phone: "text-purple-300 bg-purple-500/10 border-purple-500/30",
};

export default function SequencesPage() {
  const [seqs, setSeqs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedSeq, setSelectedSeq] = useState<any | null>(null);
  const [leads, setLeads] = useState<any[]>([]);
  const [selectedLead, setSelectedLead] = useState<string>("");
  const [preview, setPreview] = useState<any | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [creating, setCreating] = useState(false);
  const [newSeqName, setNewSeqName] = useState("");

  useEffect(() => {
    Promise.all([
      api.listSequences(),
      api.listLeads({ limit: 100 }),
    ]).then(([s, l]) => {
      setSeqs(s);
      setLeads(l);
      if (s.length > 0) setSelectedSeq(s[0]);
      setLoading(false);
    });
  }, []);

  const handlePreview = async () => {
    if (!selectedSeq || !selectedLead) return;
    setPreviewLoading(true);
    setPreview(null);
    try {
      const data = await api.getEmailsForLead(selectedSeq.id, selectedLead);
      setPreview(data);
    } catch (e) {
      console.error(e);
    } finally {
      setPreviewLoading(false);
    }
  };

  const handleCreateSequence = async () => {
    if (!newSeqName.trim()) return;
    try {
      const res = await fetch(`${BASE}/api/sequences`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: newSeqName,
          vertical: "SaaS",
          total_steps: 3,
          steps: [
            { step_number: 1, channel: "email", subject_template: "Quick thought, {first_name}", body_template: "Generated by AI", wait_days: 0 },
            { step_number: 2, channel: "email", subject_template: "Following up on {company_name}", body_template: "Generated by AI", wait_days: 3 },
            { step_number: 3, channel: "email", subject_template: "Last note from me", body_template: "Generated by AI", wait_days: 5 },
          ],
        }),
      });
      const created = await res.json();
      setSeqs((prev) => [created, ...prev]);
      setSelectedSeq(created);
      setCreating(false);
      setNewSeqName("");
    } catch (e) {
      console.error(e);
    }
  };

  const enrollLead = async () => {
    if (!selectedLead || !selectedSeq) return;
    try {
      await fetch(`${BASE}/api/leads/${selectedLead}/state`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ state: "contacted" }),
      });
      alert("Lead enrolled — agent will handle next steps based on engagement signals.");
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold mb-1">Sequences</h1>
          <p className="text-sm text-textMuted">
            Multi-touch outreach sequences. Every email is generated fresh by the AI — no templates, no substitutions.
          </p>
        </div>
        <button
          onClick={() => setCreating(true)}
          className="btn-primary flex items-center gap-2"
        >
          <Plus className="w-4 h-4" />
          New Sequence
        </button>
      </div>

      {/* New sequence modal */}
      {creating && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center">
          <div className="card w-full max-w-md space-y-4">
            <h2 className="font-semibold text-lg">Create New Sequence</h2>
            <input
              className="w-full bg-surface2 border border-border rounded-md px-3 py-2 text-sm focus:outline-none focus:border-accent"
              placeholder="Sequence name (e.g. SaaS VP Outbound)"
              value={newSeqName}
              onChange={(e) => setNewSeqName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleCreateSequence()}
            />
            <p className="text-xs text-textMuted">
              Creates a default 3-step email sequence. The AI will generate personalised emails for each lead on demand.
            </p>
            <div className="flex gap-2">
              <button onClick={handleCreateSequence} className="btn-primary flex-1">Create</button>
              <button onClick={() => setCreating(false)} className="btn-ghost flex-1">Cancel</button>
            </div>
          </div>
        </div>
      )}

      {loading && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[1, 2].map((i) => <div key={i} className="card animate-pulse h-36" />)}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-[320px_1fr] gap-6">
        {/* Sequence list */}
        <div className="space-y-3">
          <h2 className="text-xs font-semibold uppercase tracking-wide text-textMuted">Your Sequences</h2>
          {seqs.length === 0 && !loading && (
            <div className="card text-center text-textMuted py-10">
              No sequences yet. Create one above.
            </div>
          )}
          {seqs.map((s) => (
            <button
              key={s.id}
              onClick={() => { setSelectedSeq(s); setPreview(null); }}
              className={`w-full text-left card card-hover transition-all ${
                selectedSeq?.id === s.id ? "border-accent/70 bg-accent/5" : ""
              }`}
            >
              <div className="flex items-start gap-3">
                <div className="p-2 bg-accent/15 rounded-md text-accent shrink-0">
                  <Workflow className="w-4 h-4" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-sm truncate">{s.name}</div>
                  <div className="text-xs text-textMuted mt-0.5">
                    {s.vertical || "All verticals"} · {s.total_steps} steps
                  </div>
                  <div className="mt-2 flex flex-wrap gap-1">
                    {(s.steps || []).map((step: any, i: number) => (
                      <span
                        key={step.id || i}
                        className={`badge border text-[10px] ${CHANNEL_COLOR[step.channel] || "bg-surface2 text-textMuted border-border"}`}
                      >
                        {CHANNEL_ICON[step.channel] || "•"} Day {
                          (s.steps || []).slice(0, i).reduce((acc: number, st: any) => acc + (st.wait_days || 0), 0)
                        } – Step {step.step_number}
                      </span>
                    ))}
                  </div>
                </div>
                <ChevronRight className={`w-4 h-4 shrink-0 transition ${selectedSeq?.id === s.id ? "text-accent" : "text-textMuted"}`} />
              </div>
            </button>
          ))}
        </div>

        {/* Right panel */}
        {selectedSeq && (
          <div className="space-y-4">
            {/* Sequence detail */}
            <div className="card space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-accent/15 rounded-md text-accent">
                  <Workflow className="w-5 h-5" />
                </div>
                <div>
                  <h2 className="font-bold text-lg">{selectedSeq.name}</h2>
                  <p className="text-xs text-textMuted">{selectedSeq.vertical || "All verticals"} · {selectedSeq.total_steps} steps</p>
                </div>
              </div>

              {/* Step timeline */}
              <div className="space-y-2">
                <h3 className="text-xs font-semibold uppercase tracking-wide text-textMuted">Steps</h3>
                <div className="relative">
                  {(selectedSeq.steps || []).map((step: any, i: number) => {
                    const dayOffset = (selectedSeq.steps || []).slice(0, i).reduce((a: number, s: any) => a + (s.wait_days || 0), 0);
                    return (
                      <div key={step.id || i} className="flex gap-3 mb-3">
                        <div className="flex flex-col items-center">
                          <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold border ${CHANNEL_COLOR[step.channel] || "border-border text-textMuted"}`}>
                            {step.step_number}
                          </div>
                          {i < (selectedSeq.steps || []).length - 1 && (
                            <div className="w-px h-6 bg-border mt-1" />
                          )}
                        </div>
                        <div className="flex-1 pb-2">
                          <div className="flex items-center gap-2 mb-0.5">
                            <span className={`badge border text-[10px] ${CHANNEL_COLOR[step.channel] || "bg-surface2 border-border text-textMuted"}`}>
                              {CHANNEL_ICON[step.channel]} {step.channel}
                            </span>
                            <span className="text-[10px] text-textMuted flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              Day {dayOffset}
                              {step.wait_days > 0 ? ` (+${step.wait_days}d after previous)` : " (immediate)"}
                            </span>
                          </div>
                          <div className="text-sm font-medium">{step.subject_template || "AI-generated subject"}</div>
                          <div className="text-xs text-textMuted mt-0.5">
                            {step.body_template === "Generated at runtime by LLM." || !step.body_template
                              ? "✨ Email body generated by Claude for each lead individually"
                              : step.body_template}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* Lead preview + enroll panel */}
            <div className="card space-y-4">
              <div className="flex items-center gap-2">
                <Zap className="w-4 h-4 text-accent" />
                <h3 className="font-semibold text-sm">Preview & Enroll Lead</h3>
              </div>
              <p className="text-xs text-textMuted">
                Select a lead to preview the AI-generated emails for this sequence, or enroll them to start outreach.
              </p>

              <div className="flex gap-2">
                <select
                  value={selectedLead}
                  onChange={(e) => { setSelectedLead(e.target.value); setPreview(null); }}
                  className="flex-1 bg-surface2 border border-border rounded-md px-3 py-2 text-sm focus:outline-none focus:border-accent text-textPrimary"
                >
                  <option value="">Select a lead...</option>
                  {leads.map((l) => (
                    <option key={l.id} value={l.id}>
                      {[l.first_name, l.last_name].filter(Boolean).join(" ") || l.email}
                      {l.company?.name ? ` — ${l.company.name}` : ""}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handlePreview}
                  disabled={!selectedLead || previewLoading}
                  className="btn-ghost flex-1 flex items-center justify-center gap-2 disabled:opacity-40"
                >
                  <Eye className="w-4 h-4" />
                  {previewLoading ? "Generating..." : "Preview Emails"}
                </button>
                <button
                  onClick={enrollLead}
                  disabled={!selectedLead}
                  className="btn-primary flex-1 flex items-center justify-center gap-2 disabled:opacity-40"
                >
                  <Users className="w-4 h-4" />
                  Enroll Lead
                </button>
              </div>
            </div>

            {/* Email preview */}
            {previewLoading && (
              <div className="card animate-pulse space-y-3">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="space-y-2">
                    <div className="h-3 bg-surface2 rounded w-32" />
                    <div className="h-4 bg-surface2 rounded w-3/4" />
                    <div className="h-20 bg-surface2 rounded" />
                  </div>
                ))}
              </div>
            )}

            {preview && (
              <div className="space-y-3">
                <h3 className="text-xs font-semibold uppercase tracking-wide text-textMuted flex items-center gap-2">
                  <Mail className="w-3 h-3" />
                  AI-Generated Email Preview
                  <span className="text-[10px] text-accent">· Personalised for {leads.find((l) => l.id === selectedLead)?.first_name || "this lead"}</span>
                </h3>
                {(preview.emails || []).map((email: any, i: number) => (
                  <div key={i} className="card border-border/70 space-y-3">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className={`badge border text-[10px] ${
                          i === 0 ? "bg-blue-500/10 text-blue-300 border-blue-500/30" :
                          i === 1 ? "bg-purple-500/10 text-purple-300 border-purple-500/30" :
                          "bg-slate-500/10 text-slate-300 border-slate-500/30"
                        }`}>
                          Step {i + 1} · {["Intro", "Follow-up", "Break-up"][i]}
                        </span>
                        <span className="badge bg-surface2 border border-border text-[10px] text-textMuted">
                          Variant {email.ab_variant}
                        </span>
                        {email.passes_spam_check && (
                          <span className="badge bg-success/10 text-success border border-success/30 text-[10px]">
                            ✓ Spam-safe
                          </span>
                        )}
                      </div>
                      <span className="text-[10px] text-textMuted">Score: {email.spam_score?.toFixed(1)}</span>
                    </div>

                    <div>
                      <div className="text-[10px] uppercase tracking-wide text-textMuted mb-1">Subject</div>
                      <div className="font-semibold text-sm">{email.subject}</div>
                    </div>

                    <div>
                      <div className="text-[10px] uppercase tracking-wide text-textMuted mb-1">Body</div>
                      <div className="text-sm text-textMuted leading-relaxed whitespace-pre-wrap bg-surface2/50 rounded-md p-3 font-mono text-xs">
                        {email.body}
                      </div>
                    </div>

                    {email.personalisation_used && (
                      <div className="text-[10px] text-textMuted italic border-t border-border/50 pt-2">
                        ✨ {email.personalisation_used}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
